version: '3'

services:

  jenkins:
    image: gerritforge/jw2017-jenkins
    environment:
     - GIT_USER=jenkins
     - GIT_PASSWORD=secret
     - GIT_SERVER_URL=http://gerrit:8080/gerritforge/play-scala-chatroom-example
     - JENKINS_URL=http://jenkins-pipeline
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=password
    volumes:
     - jenkins-volume:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    depends_on: 
     - gerrit
     - rabbitmq
    networks:
     - local-network

  nginx:
    image: gerritforge/jw2017-nginx
    ports:
     - "80:80"
    networks:
     - local-network

  gerrit:
    image: gerritforge/jw2017-gerrit
    networks:
     - local-network
    depends_on:
     - rabbitmq
    volumes:
     - git-volume:/var/gerrit/git
     - db-volume:/var/gerrit/db
     - index-volume:/var/gerrit/index
    ports:
     - "29418:29418"

  rabbitmq:
    image: gerritforge/jw2017-rabbitmq
    networks:
     - local-network
    environment:
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=password
    ports:
     - "15672:15672"
     - "5672:5672"

  logstash-jenkins:
    image: gerritforge/jw2017-logstash
    networks:
     - local-network
    volumes:
     - logstash-output:/var/output
    depends_on: 
     - jenkins
    environment:
     - LOGSTASH_PIPELINE=jenkins

  logstash-gerrit:
    image: gerritforge/jw2017-logstash
    networks:
     - local-network
    volumes:
     - logstash-output:/var/output
    depends_on: 
     - gerrit
    environment:
     - LOGSTASH_PIPELINE=gerrit

  spark:
    image: gerritforge/jw2017-spark
    entrypoint: sleep 3650d
    volumes:
     - logstash-output:/var/output
    depends_on: 
      - elasticsearch
    networks:
     - local-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    networks:
     - local-network
    environment:
     - http.host=0.0.0.0
     - http.publish_host=127.0.0.1
    ports:
     - "9200:9200"

networks:
    local-network:
        driver: bridge

volumes:
    jenkins-volume:
    git-volume:
    db-volume:
    index-volume:
    logstash-output:
